version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel_app
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        ports:
            - "8000:80"

    nginx:
        image: nginx:latest
        container_name: laravel_nginx
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"

    postgres:
        image: postgres:latest
        container_name: laravel_postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: laravel
            POSTGRES_PASSWORD: secret
        ports:
            - "5432:5432"

    redis:
        image: redis:latest
        container_name: laravel_redis
        restart: unless-stopped
        ports:
            - "6379:6379"
